### ISSUE TITLE
Project is not open source without a license file

### ISSUE THREAD

**Issue by karan** [reivaxy/aquaMonitor#5]
Without a license, this project isn't open source and no one can use the code.

Please use something like http://choosealicense.com/ to decide what license to use. I recommend MIT or GPL.

> A novel effort by [**Add a License Please**](https://github.com/karan/add-a-license-please)

**Comment by reivaxy** [comment]
Hi,

Thanks, I know I have to, I was just a bit lazzy, but I'll do that asap, thanks :)

**Comment by reivaxy** [comment]
Done.
