### ISSUE TITLE
Monitor main power source

### ISSUE THREAD

**Issue by reivaxy** [reivaxy/aquaMonitor#6]
Main power source should be monitored to send an SMS as soon as it fails, since the battery may not last long enough to wait for temperature to drop or, if it happens during lights off schedule.

Use a resistor divider bridge on main power (12V) to drive an arduino input.

**Comment by NullFragment** [comment]
Are you asking for what resistors to use for the voltage divider?

In that case, using a normal voltage divider rule,

- R1 = 9.1k 
- R2 = 6.2k + 300 Ohm in series

Where

**Comment by NullFragment** [comment]
Are you asking for what resistors to use for the voltage divider?

In that case, using a normal voltage divider rule,
- R1 = 9.1k 
- R2 = 6.2k + 300 Ohm in series

Where
- +12V is attached to side 1 of R1
- Arduino Power is connected to the junction of R1 side 2, R2 side 1.
- GND is attached to side 2 of R2

Edit: If you're using 5V logic that is.

**Comment by reivaxy** [comment]
Hi,
Thanks, no I know how to make the divider, it's just a reminder that I need to do it :)
I think I'll use slightly higher values though, to drain even less current.
But thanks again.

**Comment by reivaxy** [comment]
Updated schematics and software, all is working nicely.
